//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShooterDownloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShooterDownloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 簡轉繁失敗.
        /// </summary>
        internal static string ErrChtConvertion {
            get {
                return ResourceManager.GetString("ErrChtConvertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} HTTP 連線失敗: {1}.
        /// </summary>
        internal static string ErrHttpRequest {
            get {
                return ResourceManager.GetString("ErrHttpRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} HTTP 回應失敗: {1}.
        /// </summary>
        internal static string ErrHttpResponse {
            get {
                return ResourceManager.GetString("ErrHttpResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 字幕下載失敗.
        /// </summary>
        internal static string ErrSubDownloadFailed {
            get {
                return ResourceManager.GetString("ErrSubDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 擷取字幕失敗: {1}.
        /// </summary>
        internal static string ErrSubExtraction {
            get {
                return ResourceManager.GetString("ErrSubExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 找不到字幕.
        /// </summary>
        internal static string ErrSubNotFound {
            get {
                return ResourceManager.GetString("ErrSubNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 字幕解壓縮失敗.
        /// </summary>
        internal static string ErrUnGZipFailed {
            get {
                return ResourceManager.GetString("ErrUnGZipFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有字幕下載完畢.
        /// </summary>
        internal static string InfoAllDownloadOk {
            get {
                return ResourceManager.GetString("InfoAllDownloadOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 簡轉繁成功.
        /// </summary>
        internal static string InfoChtConversionOk {
            get {
                return ResourceManager.GetString("InfoChtConversionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 搜尋字幕.
        /// </summary>
        internal static string InfoFindSub {
            get {
                return ResourceManager.GetString("InfoFindSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 工作取消.
        /// </summary>
        internal static string InfoJobCancelled {
            get {
                return ResourceManager.GetString("InfoJobCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 字幕不是簡體，不用轉換.
        /// </summary>
        internal static string InfoNoConversion {
            get {
                return ResourceManager.GetString("InfoNoConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 開始將字幕轉成繁體.
        /// </summary>
        internal static string InfoStartChtConversion {
            get {
                return ResourceManager.GetString("InfoStartChtConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 字幕下載完成.
        /// </summary>
        internal static string InfoSubDownloadOk {
            get {
                return ResourceManager.GetString("InfoSubDownloadOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 已找到 {1} 個字幕.
        /// </summary>
        internal static string InfoSubFound {
            get {
                return ResourceManager.GetString("InfoSubFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 射手網字幕下載工具.
        /// </summary>
        internal static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 錯誤.
        /// </summary>
        internal static string ProgressError {
            get {
                return ResourceManager.GetString("ProgressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無字幕.
        /// </summary>
        internal static string ProgressNoSub {
            get {
                return ResourceManager.GetString("ProgressNoSub", resourceCulture);
            }
        }
    }
}
